variants_reed_pipe_length = 65;
variants_reed_pipe_fastener_length = variants_reed_pipe_length / 10;
variants_reed_pipe_end_length = 12.5; // -> old value: 0.25 * variants_reed_pipe_length
variants_reed_pipe_in_diameter = 7;
variants_reed_pipe_wall_thickness = 0.8;
variants_reed_pipe_cut_prcnt = 11;
variants_reed_pipe_leaf_degree = 1.65;
variants_pipe_leaf_stem_heigth_coeff_init = 0.025;
variants_pipe_leaf_stem_heigth_coeff = 0.010;
